# Generated by Django 2.2.14 on 2020-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_auto_20200711_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(),
        ),
    ]
